#!/bin/sh

sudo apt-get install vim
sudo apt-get install mc
sudo apt-get install dnsutils
sudo apt-get install mtools
sudo apt-get install realvnc-vnc-viewer
sudo apt-get install realvnc-vnc-server

cp ~/eco/.fonts/ ~/.fonts -R
fc-cache -v -f
