#!/bin/sh

cd ~
ssh-keygen -t rsa
echo "copy ~/.ssh/id_rsa.pub to github"

git config --global user.name "LeonChristo"
git config --global user.email "leonchristo@gmail.com"
#git remote add origin git+ssh://git@github.com/leonchristo/eco.git

#git init
#echo "# Hello" > README.md
#git add t+ssh://git@github.com/leonchristo/eco.git
#git commit -m "first commit"
#git remote add origin git+ssh://git@github.com/leonchristo/eco.git
#git push -u origin master






